// <auto-generated />
using System;
using DeveloperStore.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeveloperStore.ORM.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20260623104746_ImprovePostgresNaming")]
    partial class ImprovePostgresNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeveloperStore.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sale_number");

                    b.Property<DateTimeOffset>("SoldAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sold_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("SaleNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_sales_sale_number");

                    b.HasIndex("SoldAt")
                        .HasDatabaseName("idx_sales_sold_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_sales_status");

                    b.HasIndex("Status", "SoldAt")
                        .HasDatabaseName("idx_sales_status_sold_at");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("DeveloperStore.Domain.Entities.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sale_items");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("idx_sale_items_sale_id");

                    b.ToTable("sale_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_sale_items_discount_range", "discount_percentage >= 0 AND discount_percentage <= 1");

                            t.HasCheckConstraint("ck_sale_items_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_sale_items_unit_price_non_neg", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("DeveloperStore.Domain.Entities.Sale", b =>
                {
                    b.OwnsOne("DeveloperStore.Domain.ValueObjects.BranchReference", "Branch", b1 =>
                        {
                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("branch_name");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("branch_external_id");

                            b1.HasKey("SaleId");

                            b1.ToTable("sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.OwnsOne("DeveloperStore.Domain.ValueObjects.CustomerReference", "Customer", b1 =>
                        {
                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("customer_name");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("customer_external_id");

                            b1.HasKey("SaleId");

                            b1.ToTable("sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.Navigation("Branch")
                        .IsRequired();

                    b.Navigation("Customer")
                        .IsRequired();
                });

            modelBuilder.Entity("DeveloperStore.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("DeveloperStore.Domain.Entities.Sale", null)
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_items_sales");

                    b.OwnsOne("DeveloperStore.Domain.ValueObjects.ProductReference", "Product", b1 =>
                        {
                            b1.Property<Guid>("SaleItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("product_name");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("product_external_id");

                            b1.HasKey("SaleItemId");

                            b1.ToTable("sale_items");

                            b1.WithOwner()
                                .HasForeignKey("SaleItemId");
                        });

                    b.Navigation("Product")
                        .IsRequired();
                });

            modelBuilder.Entity("DeveloperStore.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
