// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DeveloperStore.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CancelarItemDeVendaFeature : object, Xunit.IClassFixture<CancelarItemDeVendaFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features", "Cancelar item de venda", "  Como consumidor da API de vendas\n  Quero cancelar um item individual de uma ven" +
                "da\n  Para que o item seja marcado como cancelado e o total da venda seja recalcu" +
                "lado", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CancelSaleItem.feature"
#line hidden
        
        public CancelarItemDeVendaFeature(CancelarItemDeVendaFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelar um item de venda com dois itens recalcula o TotalAmount")]
        [Xunit.TraitAttribute("FeatureTitle", "Cancelar item de venda")]
        [Xunit.TraitAttribute("Description", "Cancelar um item de venda com dois itens recalcula o TotalAmount")]
        public async global::System.Threading.Tasks.Task CancelarUmItemDeVendaComDoisItensRecalculaOTotalAmount()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelar um item de venda com dois itens recalcula o TotalAmount", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que existe uma venda ativa com dois itens cadastrada no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.WhenAsync("eu cancelar o primeiro item da venda", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 10
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 11
    await testRunner.AndAsync("o item cancelado deve estar marcado como cancelado na resposta", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 12
    await testRunner.AndAsync("a venda deve permanecer com Status NotCancelled", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 13
    await testRunner.AndAsync("o TotalAmount da venda no banco deve refletir apenas o item não cancelado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelar o último item ativo torna a venda Cancelled automaticamente")]
        [Xunit.TraitAttribute("FeatureTitle", "Cancelar item de venda")]
        [Xunit.TraitAttribute("Description", "Cancelar o último item ativo torna a venda Cancelled automaticamente")]
        public async global::System.Threading.Tasks.Task CancelarOUltimoItemAtivoTornaAVendaCancelledAutomaticamente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelar o último item ativo torna a venda Cancelled automaticamente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
    await testRunner.GivenAsync("que existe uma venda ativa com um único item cadastrada no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 17
    await testRunner.WhenAsync("eu cancelar o único item da venda", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 18
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 19
    await testRunner.AndAsync("o status da venda retornada deve ser \"Cancelled\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 20
    await testRunner.AndAsync("a venda com item cancelado deve existir no banco com todos os itens cancelados", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelar item já cancelado é idempotente e retorna 200")]
        [Xunit.TraitAttribute("FeatureTitle", "Cancelar item de venda")]
        [Xunit.TraitAttribute("Description", "Cancelar item já cancelado é idempotente e retorna 200")]
        public async global::System.Threading.Tasks.Task CancelarItemJaCanceladoEIdempotenteERetorna200()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelar item já cancelado é idempotente e retorna 200", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
    await testRunner.GivenAsync("que existe uma venda ativa com um item já cancelado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 24
    await testRunner.WhenAsync("eu cancelar novamente o item já cancelado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 25
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 26
    await testRunner.AndAsync("o item cancelado deve estar marcado como cancelado na resposta", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelar item em venda cancelada retorna 409")]
        [Xunit.TraitAttribute("FeatureTitle", "Cancelar item de venda")]
        [Xunit.TraitAttribute("Description", "Cancelar item em venda cancelada retorna 409")]
        public async global::System.Threading.Tasks.Task CancelarItemEmVendaCanceladaRetorna409()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelar item em venda cancelada retorna 409", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
    await testRunner.GivenAsync("que existe uma venda totalmente cancelada para cancelamento de item", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 30
    await testRunner.WhenAsync("eu tentar cancelar um item dessa venda cancelada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 31
    await testRunner.ThenAsync("a resposta deve ter status 409", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 32
    await testRunner.AndAsync("o tipo do erro deve ser \"sale_state_conflict\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelar item com saleId inválido retorna 422")]
        [Xunit.TraitAttribute("FeatureTitle", "Cancelar item de venda")]
        [Xunit.TraitAttribute("Description", "Cancelar item com saleId inválido retorna 422")]
        public async global::System.Threading.Tasks.Task CancelarItemComSaleIdInvalidoRetorna422()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelar item com saleId inválido retorna 422", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
    await testRunner.GivenAsync("que o saleId informado para cancelamento de item é inválido e não é um UUID", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 36
    await testRunner.WhenAsync("eu tentar cancelar um item com o saleId inválido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 37
    await testRunner.ThenAsync("a resposta deve ter status 422", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 38
    await testRunner.AndAsync("o código do erro de validação deve ser \"sale_id_invalid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelar item com itemId inválido retorna 422")]
        [Xunit.TraitAttribute("FeatureTitle", "Cancelar item de venda")]
        [Xunit.TraitAttribute("Description", "Cancelar item com itemId inválido retorna 422")]
        public async global::System.Threading.Tasks.Task CancelarItemComItemIdInvalidoRetorna422()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelar item com itemId inválido retorna 422", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
    await testRunner.GivenAsync("que existe uma venda ativa cadastrada no sistema para cancelamento de item", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 42
    await testRunner.WhenAsync("eu tentar cancelar um item com itemId inválido dessa venda", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 43
    await testRunner.ThenAsync("a resposta deve ter status 422", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 44
    await testRunner.AndAsync("o código do erro de validação deve ser \"item_id_invalid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelar item com saleId inexistente retorna 404")]
        [Xunit.TraitAttribute("FeatureTitle", "Cancelar item de venda")]
        [Xunit.TraitAttribute("Description", "Cancelar item com saleId inexistente retorna 404")]
        public async global::System.Threading.Tasks.Task CancelarItemComSaleIdInexistenteRetorna404()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelar item com saleId inexistente retorna 404", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
    await testRunner.GivenAsync("que não existe nenhuma venda com o saleId informado para cancelamento de item", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 48
    await testRunner.WhenAsync("eu tentar cancelar um item com o saleId inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 49
    await testRunner.ThenAsync("a resposta deve ter status 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 50
    await testRunner.AndAsync("o tipo do erro deve ser \"resource_not_found\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelar item com itemId inexistente retorna 404")]
        [Xunit.TraitAttribute("FeatureTitle", "Cancelar item de venda")]
        [Xunit.TraitAttribute("Description", "Cancelar item com itemId inexistente retorna 404")]
        public async global::System.Threading.Tasks.Task CancelarItemComItemIdInexistenteRetorna404()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelar item com itemId inexistente retorna 404", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
    await testRunner.GivenAsync("que existe uma venda ativa cadastrada no sistema para cancelamento de item", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 54
    await testRunner.WhenAsync("eu tentar cancelar um item com itemId inexistente dessa venda", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 55
    await testRunner.ThenAsync("a resposta deve ter status 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 56
    await testRunner.AndAsync("o tipo do erro deve ser \"resource_not_found\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CancelarItemDeVendaFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CancelarItemDeVendaFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
