// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DeveloperStore.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CriarVendaFeature : object, Xunit.IClassFixture<CriarVendaFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features", "Criar Venda", "  Como consumidor da API de vendas\n  Quero criar novas vendas\n  Para registrar tr" +
                "ansações comerciais no sistema", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateSale.feature"
#line hidden
        
        public CriarVendaFeature(CriarVendaFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar venda válida com um item")]
        [Xunit.TraitAttribute("FeatureTitle", "Criar Venda")]
        [Xunit.TraitAttribute("Description", "Criar venda válida com um item")]
        public async global::System.Threading.Tasks.Task CriarVendaValidaComUmItem()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Criar venda válida com um item", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("dados válidos de venda com um item", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.WhenAsync("envio POST para /api/sales", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 10
    await testRunner.ThenAsync("recebo status 201 Created", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 11
    await testRunner.AndAsync("a venda está persistida no banco com os dados corretos", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar venda com múltiplos itens")]
        [Xunit.TraitAttribute("FeatureTitle", "Criar Venda")]
        [Xunit.TraitAttribute("Description", "Criar venda com múltiplos itens")]
        public async global::System.Threading.Tasks.Task CriarVendaComMultiplosItens()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Criar venda com múltiplos itens", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
    await testRunner.GivenAsync("dados válidos de venda com múltiplos itens", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 15
    await testRunner.WhenAsync("envio POST para /api/sales", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 16
    await testRunner.ThenAsync("recebo status 201 Created", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 17
    await testRunner.AndAsync("o totalAmount da resposta é igual à soma dos itens", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Campo obrigatório ausente retorna 422")]
        [Xunit.TraitAttribute("FeatureTitle", "Criar Venda")]
        [Xunit.TraitAttribute("Description", "Campo obrigatório ausente retorna 422")]
        [Xunit.InlineDataAttribute("saleNumber", "sale_number_required", new string[0])]
        [Xunit.InlineDataAttribute("soldAt", "sold_at_required", new string[0])]
        [Xunit.InlineDataAttribute("customerExternalId", "customer_external_id_required", new string[0])]
        [Xunit.InlineDataAttribute("customerName", "customer_name_required", new string[0])]
        [Xunit.InlineDataAttribute("branchExternalId", "branch_external_id_required", new string[0])]
        [Xunit.InlineDataAttribute("branchName", "branch_name_required", new string[0])]
        public async global::System.Threading.Tasks.Task CampoObrigatorioAusenteRetorna422(string campo, string codigo_Erro, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("campo", campo);
            argumentsOfScenario.Add("codigo_erro", codigo_Erro);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Campo obrigatório ausente retorna 422", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync(string.Format("uma requisição de criação de venda sem o campo \"{0}\"", campo), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 21
    await testRunner.WhenAsync("envio POST para /api/sales", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 22
    await testRunner.ThenAsync("recebo status 422 Unprocessable Entity", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 23
    await testRunner.AndAsync(string.Format("o código de erro \"{0}\" está presente na resposta", codigo_Erro), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar venda sem itens retorna 422")]
        [Xunit.TraitAttribute("FeatureTitle", "Criar Venda")]
        [Xunit.TraitAttribute("Description", "Criar venda sem itens retorna 422")]
        public async global::System.Threading.Tasks.Task CriarVendaSemItensRetorna422()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Criar venda sem itens retorna 422", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
    await testRunner.GivenAsync("dados válidos de venda sem itens", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 36
    await testRunner.WhenAsync("envio POST para /api/sales", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 37
    await testRunner.ThenAsync("recebo status 422 Unprocessable Entity", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 38
    await testRunner.AndAsync("o código de erro \"items_required\" está presente na resposta", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Quantidade de item inválida retorna 422")]
        [Xunit.TraitAttribute("FeatureTitle", "Criar Venda")]
        [Xunit.TraitAttribute("Description", "Quantidade de item inválida retorna 422")]
        [Xunit.InlineDataAttribute("0", "quantity_must_be_positive", new string[0])]
        [Xunit.InlineDataAttribute("21", "quantity_limit_exceeded", new string[0])]
        public async global::System.Threading.Tasks.Task QuantidadeDeItemInvalidaRetorna422(string quantidade, string codigo_Erro, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("quantidade", quantidade);
            argumentsOfScenario.Add("codigo_erro", codigo_Erro);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Quantidade de item inválida retorna 422", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
    await testRunner.GivenAsync(string.Format("dados válidos de venda com um item de quantidade {0}", quantidade), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 42
    await testRunner.WhenAsync("envio POST para /api/sales", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 43
    await testRunner.ThenAsync("recebo status 422 Unprocessable Entity", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 44
    await testRunner.AndAsync(string.Format("o código de erro \"{0}\" está presente na resposta", codigo_Erro), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Preço unitário zero retorna 422")]
        [Xunit.TraitAttribute("FeatureTitle", "Criar Venda")]
        [Xunit.TraitAttribute("Description", "Preço unitário zero retorna 422")]
        public async global::System.Threading.Tasks.Task PrecoUnitarioZeroRetorna422()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preço unitário zero retorna 422", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
    await testRunner.GivenAsync("dados válidos de venda com um item com preço unitário zero", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 53
    await testRunner.WhenAsync("envio POST para /api/sales", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 54
    await testRunner.ThenAsync("recebo status 422 Unprocessable Entity", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 55
    await testRunner.AndAsync("o código de erro \"unit_price_must_be_positive\" está presente na resposta", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Número de venda duplicado retorna 409")]
        [Xunit.TraitAttribute("FeatureTitle", "Criar Venda")]
        [Xunit.TraitAttribute("Description", "Número de venda duplicado retorna 409")]
        public async global::System.Threading.Tasks.Task NumeroDeVendaDuplicadoRetorna409()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Número de venda duplicado retorna 409", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
    await testRunner.GivenAsync("uma venda com o número \"BDD-DUP-001\" já existe no banco", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 59
    await testRunner.WhenAsync("envio POST para /api/sales com o número \"BDD-DUP-001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 60
    await testRunner.ThenAsync("recebo status 409 Conflict", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 61
    await testRunner.AndAsync("o código de erro \"sale_number_conflict\" está presente na resposta", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 62
    await testRunner.AndAsync("existe apenas uma venda com número \"BDD-DUP-001\" no banco", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Total do item calculado corretamente")]
        [Xunit.TraitAttribute("FeatureTitle", "Criar Venda")]
        [Xunit.TraitAttribute("Description", "Total do item calculado corretamente")]
        [Xunit.InlineDataAttribute("1", "10.00", "10.00", new string[0])]
        [Xunit.InlineDataAttribute("3", "10.00", "30.00", new string[0])]
        [Xunit.InlineDataAttribute("4", "10.00", "36.00", new string[0])]
        [Xunit.InlineDataAttribute("5", "4.50", "20.25", new string[0])]
        [Xunit.InlineDataAttribute("9", "10.00", "81.00", new string[0])]
        [Xunit.InlineDataAttribute("10", "10.00", "80.00", new string[0])]
        [Xunit.InlineDataAttribute("20", "99.99", "1599.84", new string[0])]
        public async global::System.Threading.Tasks.Task TotalDoItemCalculadoCorretamente(string quantidade, string preco, string total_Esperado, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("quantidade", quantidade);
            argumentsOfScenario.Add("preco", preco);
            argumentsOfScenario.Add("total_esperado", total_Esperado);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Total do item calculado corretamente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
    await testRunner.GivenAsync(string.Format("dados válidos de venda com um item de quantidade {0} e preço {1}", quantidade, preco), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 66
    await testRunner.WhenAsync("envio POST para /api/sales", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 67
    await testRunner.ThenAsync("recebo status 201 Created", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 68
    await testRunner.AndAsync(string.Format("o totalAmount do item na resposta é {0}", total_Esperado), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Produto duplicado na mesma venda retorna 422")]
        [Xunit.TraitAttribute("FeatureTitle", "Criar Venda")]
        [Xunit.TraitAttribute("Description", "Produto duplicado na mesma venda retorna 422")]
        public async global::System.Threading.Tasks.Task ProdutoDuplicadoNaMesmaVendaRetorna422()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Produto duplicado na mesma venda retorna 422", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 80
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 81
    await testRunner.GivenAsync("dados de venda com dois itens com o mesmo productExternalId", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 82
    await testRunner.WhenAsync("envio POST para /api/sales", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 83
    await testRunner.ThenAsync("recebo status 422 Unprocessable Entity", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 84
    await testRunner.AndAsync("o código de erro \"duplicate_product_in_sale\" está presente na resposta", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CriarVendaFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CriarVendaFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
