// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DeveloperStore.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BuscarVendaPorIDFeature : object, Xunit.IClassFixture<BuscarVendaPorIDFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features", "Buscar venda por ID", "  Como consumidor da API de vendas\n  Quero buscar uma venda pelo seu identificado" +
                "r\n  Para obter os detalhes completos da venda", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetSale.feature"
#line hidden
        
        public BuscarVendaPorIDFeature(BuscarVendaPorIDFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar venda existente pelo ID retorna 200 com dados corretos")]
        [Xunit.TraitAttribute("FeatureTitle", "Buscar venda por ID")]
        [Xunit.TraitAttribute("Description", "Buscar venda existente pelo ID retorna 200 com dados corretos")]
        public async global::System.Threading.Tasks.Task BuscarVendaExistentePeloIDRetorna200ComDadosCorretos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar venda existente pelo ID retorna 200 com dados corretos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que existe uma venda cadastrada no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.WhenAsync("eu buscar a venda pelo ID cadastrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 10
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 11
    await testRunner.AndAsync("os dados da venda retornados devem corresponder à venda cadastrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 12
    await testRunner.AndAsync("a venda deve existir no banco de dados com os dados corretos", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar venda com ID inexistente retorna 404")]
        [Xunit.TraitAttribute("FeatureTitle", "Buscar venda por ID")]
        [Xunit.TraitAttribute("Description", "Buscar venda com ID inexistente retorna 404")]
        public async global::System.Threading.Tasks.Task BuscarVendaComIDInexistenteRetorna404()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar venda com ID inexistente retorna 404", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("que não existe nenhuma venda com o ID informado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 16
    await testRunner.WhenAsync("eu buscar a venda pelo ID inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 17
    await testRunner.ThenAsync("a resposta deve ter status 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 18
    await testRunner.AndAsync("o tipo do erro deve ser \"resource_not_found\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar venda com ID inválido retorna 422")]
        [Xunit.TraitAttribute("FeatureTitle", "Buscar venda por ID")]
        [Xunit.TraitAttribute("Description", "Buscar venda com ID inválido retorna 422")]
        public async global::System.Threading.Tasks.Task BuscarVendaComIDInvalidoRetorna422()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar venda com ID inválido retorna 422", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
    await testRunner.GivenAsync("que o ID informado é inválido e não é um UUID", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 22
    await testRunner.WhenAsync("eu buscar a venda pelo ID inválido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 23
    await testRunner.ThenAsync("a resposta deve ter status 422", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 24
    await testRunner.AndAsync("o código do erro de validação deve ser \"sale_id_invalid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await BuscarVendaPorIDFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await BuscarVendaPorIDFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
