// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DeveloperStore.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ListarVendasFeature : object, Xunit.IClassFixture<ListarVendasFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features", "Listar vendas", "  Como consumidor da API de vendas\n  Quero listar as vendas com suporte a filtros" +
                ", ordenação e paginação\n  Para consultar e monitorar as vendas do sistema", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ListSales.feature"
#line hidden
        
        public ListarVendasFeature(ListarVendasFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar vendas com paginação padrão retorna 200 com dados corretos")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Listar vendas com paginação padrão retorna 200 com dados corretos")]
        public async global::System.Threading.Tasks.Task ListarVendasComPaginacaoPadraoRetorna200ComDadosCorretos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar vendas com paginação padrão retorna 200 com dados corretos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que existem 3 vendas cadastradas com prefixo \"LIST-PAD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.WhenAsync("eu listar as vendas sem filtros", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 10
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 11
    await testRunner.AndAsync("o response deve conter ao menos 3 vendas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 12
    await testRunner.AndAsync("o pageNumber do response deve ser 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 13
    await testRunner.AndAsync("o pageSize do response deve ser 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filtrar por número da venda exato retorna apenas a venda correspondente")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Filtrar por número da venda exato retorna apenas a venda correspondente")]
        public async global::System.Threading.Tasks.Task FiltrarPorNumeroDaVendaExatoRetornaApenasAVendaCorrespondente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filtrar por número da venda exato retorna apenas a venda correspondente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
    await testRunner.GivenAsync("que existem vendas cadastradas com prefixo \"LIST-EXACT\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 17
    await testRunner.AndAsync("que uma das vendas tem saleNumber \"LIST-EXACT-001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 18
    await testRunner.WhenAsync("eu listar as vendas com filtro saleNumber igual a \"LIST-EXACT-001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 19
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 20
    await testRunner.AndAsync("o response deve conter exatamente 1 venda", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 21
    await testRunner.AndAsync("a venda retornada deve ter saleNumber \"LIST-EXACT-001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filtrar por número da venda com wildcard retorna múltiplas vendas")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Filtrar por número da venda com wildcard retorna múltiplas vendas")]
        public async global::System.Threading.Tasks.Task FiltrarPorNumeroDaVendaComWildcardRetornaMultiplasVendas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filtrar por número da venda com wildcard retorna múltiplas vendas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.GivenAsync("que existem 3 vendas cadastradas com prefixo \"LIST-WILD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 25
    await testRunner.WhenAsync("eu listar as vendas com filtro saleNumber usando wildcard \"LIST-WILD*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 26
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 27
    await testRunner.AndAsync("o response deve conter exatamente 3 vendas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 28
    await testRunner.AndAsync("todas as vendas retornadas devem ter saleNumber iniciando com \"LIST-WILD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filtrar por nome do cliente retorna apenas vendas do cliente")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Filtrar por nome do cliente retorna apenas vendas do cliente")]
        public async global::System.Threading.Tasks.Task FiltrarPorNomeDoClienteRetornaApenasVendasDoCliente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filtrar por nome do cliente retorna apenas vendas do cliente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
    await testRunner.GivenAsync("que existem 2 vendas cadastradas com prefixo \"LIST-CUST\" para o cliente \"Alice Sa" +
                        "ntos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 32
    await testRunner.AndAsync("que existe 1 venda cadastrada com prefixo \"LIST-CUST\" para o cliente \"Bob Lima\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 33
    await testRunner.WhenAsync("eu listar as vendas com filtro customerName igual a \"Alice Santos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 34
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 35
    await testRunner.AndAsync("o response deve conter exatamente 2 vendas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 36
    await testRunner.AndAsync("todas as vendas retornadas devem pertencer ao cliente \"Alice Santos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filtrar por nome da filial retorna apenas vendas da filial")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Filtrar por nome da filial retorna apenas vendas da filial")]
        public async global::System.Threading.Tasks.Task FiltrarPorNomeDaFilialRetornaApenasVendasDaFilial()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filtrar por nome da filial retorna apenas vendas da filial", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync("que existem 2 vendas cadastradas com prefixo \"LIST-BRNCH\" para a filial \"Filial C" +
                        "entral\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 40
    await testRunner.AndAsync("que existe 1 venda cadastrada com prefixo \"LIST-BRNCH\" para a filial \"Filial Nort" +
                        "e\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 41
    await testRunner.WhenAsync("eu listar as vendas com filtro branchName igual a \"Filial Central\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 42
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 43
    await testRunner.AndAsync("o response deve conter exatamente 2 vendas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 44
    await testRunner.AndAsync("todas as vendas retornadas devem pertencer à filial \"Filial Central\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filtrar por status Cancelled retorna apenas vendas canceladas")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Filtrar por status Cancelled retorna apenas vendas canceladas")]
        public async global::System.Threading.Tasks.Task FiltrarPorStatusCancelledRetornaApenasVendasCanceladas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filtrar por status Cancelled retorna apenas vendas canceladas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
    await testRunner.GivenAsync("que existem 2 vendas cadastradas com prefixo \"LIST-STS\" e a primeira está cancela" +
                        "da", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 48
    await testRunner.WhenAsync("eu listar as vendas com filtro status igual a \"Cancelled\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 49
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 50
    await testRunner.AndAsync("todas as vendas retornadas devem ter status \"Cancelled\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filtrar por status NotCancelled retorna apenas vendas ativas")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Filtrar por status NotCancelled retorna apenas vendas ativas")]
        public async global::System.Threading.Tasks.Task FiltrarPorStatusNotCancelledRetornaApenasVendasAtivas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filtrar por status NotCancelled retorna apenas vendas ativas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
    await testRunner.GivenAsync("que existem 2 vendas cadastradas com prefixo \"LIST-STSN\" e a primeira está cancel" +
                        "ada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 54
    await testRunner.WhenAsync("eu listar as vendas com filtro status igual a \"NotCancelled\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 55
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 56
    await testRunner.AndAsync("todas as vendas retornadas devem ter status \"NotCancelled\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filtrar por intervalo de datas retorna apenas vendas no período")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Filtrar por intervalo de datas retorna apenas vendas no período")]
        public async global::System.Threading.Tasks.Task FiltrarPorIntervaloDeDatasRetornaApenasVendasNoPeriodo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filtrar por intervalo de datas retorna apenas vendas no período", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
    await testRunner.GivenAsync("que existem 3 vendas com prefixo \"LIST-DT\" com datas distribuídas em janeiro de 2" +
                        "024", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 60
    await testRunner.WhenAsync("eu listar as vendas com _minSoldAt \"2024-01-10T00:00:00Z\" e _maxSoldAt \"2024-01-2" +
                        "0T23:59:59Z\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 61
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 62
    await testRunner.AndAsync("apenas vendas dentro do intervalo de datas devem ser retornadas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ordenar por número da venda ascendente retorna vendas na ordem correta")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Ordenar por número da venda ascendente retorna vendas na ordem correta")]
        public async global::System.Threading.Tasks.Task OrdenarPorNumeroDaVendaAscendenteRetornaVendasNaOrdemCorreta()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ordenar por número da venda ascendente retorna vendas na ordem correta", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
    await testRunner.GivenAsync("que existem 3 vendas cadastradas com prefixo \"LIST-ORD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 66
    await testRunner.WhenAsync("eu listar as vendas com ordenação \"_order=saleNumber asc\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 67
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 68
    await testRunner.AndAsync("os saleNumbers das vendas retornadas devem estar em ordem ascendente", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Paginação com múltiplas páginas - página 1")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Paginação com múltiplas páginas - página 1")]
        public async global::System.Threading.Tasks.Task PaginacaoComMultiplasPaginas_Pagina1()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Paginação com múltiplas páginas - página 1", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 71
    await testRunner.GivenAsync("que existem 5 vendas cadastradas com prefixo \"LIST-PG\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 72
    await testRunner.WhenAsync("eu listar as vendas com _page=1 e _size=3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 73
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 74
    await testRunner.AndAsync("o pageNumber do response deve ser 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 75
    await testRunner.AndAsync("o pageSize do response deve ser 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 76
    await testRunner.AndAsync("o totalCount deve ser pelo menos 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 77
    await testRunner.AndAsync("o totalPages deve ser pelo menos 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Paginação com múltiplas páginas - página 2")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Paginação com múltiplas páginas - página 2")]
        public async global::System.Threading.Tasks.Task PaginacaoComMultiplasPaginas_Pagina2()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Paginação com múltiplas páginas - página 2", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 80
    await testRunner.GivenAsync("que existem 5 vendas cadastradas com prefixo \"LIST-PG2\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 81
    await testRunner.WhenAsync("eu listar as vendas com prefixo \"LIST-PG2\" _page=2 e _size=3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 82
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 83
    await testRunner.AndAsync("o pageNumber do response deve ser 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Suporte ao alias legado customer= filtra por nome do cliente")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Suporte ao alias legado customer= filtra por nome do cliente")]
        public async global::System.Threading.Tasks.Task SuporteAoAliasLegadoCustomerFiltraPorNomeDoCliente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Suporte ao alias legado customer= filtra por nome do cliente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 85
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 86
    await testRunner.GivenAsync("que existem 2 vendas cadastradas com prefixo \"LIST-ALI\" para o cliente \"Carlos Ne" +
                        "to\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 87
    await testRunner.WhenAsync("eu listar as vendas com o parâmetro legado \"customer\" igual a \"Carlos Neto\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 88
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 89
    await testRunner.AndAsync("o response deve conter ao menos 2 vendas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 90
    await testRunner.AndAsync("todas as vendas retornadas devem pertencer ao cliente \"Carlos Neto\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Suporte ao alias legado branch= filtra por nome da filial")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Suporte ao alias legado branch= filtra por nome da filial")]
        public async global::System.Threading.Tasks.Task SuporteAoAliasLegadoBranchFiltraPorNomeDaFilial()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Suporte ao alias legado branch= filtra por nome da filial", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 92
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 93
    await testRunner.GivenAsync("que existem 2 vendas cadastradas com prefixo \"LIST-ALB\" para a filial \"Filial Sul" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 94
    await testRunner.WhenAsync("eu listar as vendas com o parâmetro legado \"branch\" igual a \"Filial Sul\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 95
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 96
    await testRunner.AndAsync("o response deve conter ao menos 2 vendas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 97
    await testRunner.AndAsync("todas as vendas retornadas devem pertencer à filial \"Filial Sul\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filtro sem resultados retorna lista vazia com 200")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Filtro sem resultados retorna lista vazia com 200")]
        public async global::System.Threading.Tasks.Task FiltroSemResultadosRetornaListaVaziaCom200()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filtro sem resultados retorna lista vazia com 200", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 99
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 100
    await testRunner.GivenAsync("que não existem vendas com o saleNumber \"LIST-EMPTY-999\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 101
    await testRunner.WhenAsync("eu listar as vendas com filtro saleNumber igual a \"LIST-EMPTY-999\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 102
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 103
    await testRunner.AndAsync("o response deve conter exatamente 0 vendas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 104
    await testRunner.AndAsync("o totalCount deve ser 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Parâmetros de paginação inválidos retornam 422 com código correto")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Parâmetros de paginação inválidos retornam 422 com código correto")]
        [Xunit.InlineDataAttribute("_page", "0", "page_number_invalid", new string[0])]
        [Xunit.InlineDataAttribute("_size", "101", "page_size_invalid", new string[0])]
        public async global::System.Threading.Tasks.Task ParametrosDePaginacaoInvalidosRetornam422ComCodigoCorreto(string parametro, string valor, string codigo, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("parametro", parametro);
            argumentsOfScenario.Add("valor", valor);
            argumentsOfScenario.Add("codigo", codigo);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Parâmetros de paginação inválidos retornam 422 com código correto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 106
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 107
    await testRunner.WhenAsync(string.Format("eu listar as vendas com \"{0}\"=\"{1}\"", parametro, valor), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 108
    await testRunner.ThenAsync("a resposta deve ter status 422", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 109
    await testRunner.AndAsync(string.Format("o código do erro de validação deve ser \"{0}\"", codigo), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ordenação por campo inválido retorna 422 com código order_invalid")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Ordenação por campo inválido retorna 422 com código order_invalid")]
        public async global::System.Threading.Tasks.Task OrdenacaoPorCampoInvalidoRetorna422ComCodigoOrder_Invalid()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ordenação por campo inválido retorna 422 com código order_invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 116
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 117
    await testRunner.WhenAsync("eu listar as vendas com ordenação \"_order=campoInexistente asc\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 118
    await testRunner.ThenAsync("a resposta deve ter status 422", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 119
    await testRunner.AndAsync("o código do erro de validação deve ser \"order_invalid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Intervalo de datas invertido retorna 422 com código sold_at_range_invalid")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "Intervalo de datas invertido retorna 422 com código sold_at_range_invalid")]
        public async global::System.Threading.Tasks.Task IntervaloDeDatasInvertidoRetorna422ComCodigoSold_At_Range_Invalid()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Intervalo de datas invertido retorna 422 com código sold_at_range_invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 121
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 122
    await testRunner.WhenAsync("eu listar as vendas com _minSoldAt \"2024-06-30T00:00:00Z\" e _maxSoldAt \"2024-01-0" +
                        "1T00:00:00Z\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 123
    await testRunner.ThenAsync("a resposta deve ter status 422", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 124
    await testRunner.AndAsync("o código do erro de validação deve ser \"sold_at_range_invalid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="O totalCount no response corresponde ao número de registros no banco")]
        [Xunit.TraitAttribute("FeatureTitle", "Listar vendas")]
        [Xunit.TraitAttribute("Description", "O totalCount no response corresponde ao número de registros no banco")]
        public async global::System.Threading.Tasks.Task OTotalCountNoResponseCorrespondeAoNumeroDeRegistrosNoBanco()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("O totalCount no response corresponde ao número de registros no banco", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 126
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 127
    await testRunner.GivenAsync("que existem 3 vendas cadastradas com prefixo \"LIST-CNT\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 128
    await testRunner.WhenAsync("eu listar as vendas com filtro saleNumber usando wildcard \"LIST-CNT*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 129
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 130
    await testRunner.AndAsync("o totalCount corresponde ao número de registros no banco com prefixo \"LIST-CNT\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ListarVendasFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ListarVendasFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
