// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DeveloperStore.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AtualizarVendaFeature : object, Xunit.IClassFixture<AtualizarVendaFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features", "Atualizar venda", "  Como consumidor da API de vendas\n  Quero atualizar os dados de uma venda existe" +
                "nte\n  Para manter as informações de vendas sempre corretas", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UpdateSale.feature"
#line hidden
        
        public AtualizarVendaFeature(AtualizarVendaFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar venda existente com novos dados retorna 200 com dados atualizados")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualizar venda")]
        [Xunit.TraitAttribute("Description", "Atualizar venda existente com novos dados retorna 200 com dados atualizados")]
        public async global::System.Threading.Tasks.Task AtualizarVendaExistenteComNovosDadosRetorna200ComDadosAtualizados()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar venda existente com novos dados retorna 200 com dados atualizados", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que existe uma venda cadastrada para atualização", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.WhenAsync("eu atualizar a venda com novos dados de cliente e filial", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 10
    await testRunner.ThenAsync("a resposta de atualização deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 11
    await testRunner.AndAsync("os dados da venda atualizada devem refletir as novas informações", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 12
    await testRunner.AndAsync("os novos dados devem estar persistidos no banco de dados", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar venda mantendo o mesmo saleNumber retorna 200")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualizar venda")]
        [Xunit.TraitAttribute("Description", "Atualizar venda mantendo o mesmo saleNumber retorna 200")]
        public async global::System.Threading.Tasks.Task AtualizarVendaMantendoOMesmoSaleNumberRetorna200()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar venda mantendo o mesmo saleNumber retorna 200", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("que existe uma venda cadastrada para manter o mesmo número", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 16
    await testRunner.WhenAsync("eu atualizar a venda mantendo o mesmo saleNumber", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 17
    await testRunner.ThenAsync("a resposta de atualização deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 18
    await testRunner.AndAsync("os dados da venda retornada devem conter o mesmo saleNumber", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar venda com ID inválido retorna 422")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualizar venda")]
        [Xunit.TraitAttribute("Description", "Atualizar venda com ID inválido retorna 422")]
        public async global::System.Threading.Tasks.Task AtualizarVendaComIDInvalidoRetorna422()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar venda com ID inválido retorna 422", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
    await testRunner.GivenAsync("que o ID da venda a ser atualizada é inválido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 22
    await testRunner.WhenAsync("eu tentar atualizar a venda com ID inválido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 23
    await testRunner.ThenAsync("a resposta de atualização deve ter status 422", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 24
    await testRunner.AndAsync("o código do erro de atualização deve ser \"sale_id_invalid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar venda com ID inexistente retorna 404")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualizar venda")]
        [Xunit.TraitAttribute("Description", "Atualizar venda com ID inexistente retorna 404")]
        public async global::System.Threading.Tasks.Task AtualizarVendaComIDInexistenteRetorna404()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar venda com ID inexistente retorna 404", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 27
    await testRunner.GivenAsync("que não existe venda com o ID informado para atualização", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 28
    await testRunner.WhenAsync("eu tentar atualizar a venda inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 29
    await testRunner.ThenAsync("a resposta de atualização deve ter status 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 30
    await testRunner.AndAsync("o tipo do erro de atualização deve ser \"resource_not_found\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Alterar saleNumber para número já existente retorna 409")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualizar venda")]
        [Xunit.TraitAttribute("Description", "Alterar saleNumber para número já existente retorna 409")]
        public async global::System.Threading.Tasks.Task AlterarSaleNumberParaNumeroJaExistenteRetorna409()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Alterar saleNumber para número já existente retorna 409", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
    await testRunner.GivenAsync("que existem duas vendas cadastradas com números distintos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 34
    await testRunner.WhenAsync("eu tentar atualizar a primeira venda com o saleNumber da segunda venda", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 35
    await testRunner.ThenAsync("a resposta de atualização deve ter status 409", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 36
    await testRunner.AndAsync("o tipo do erro de atualização deve ser \"sale_number_conflict\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar venda cancelada retorna 409")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualizar venda")]
        [Xunit.TraitAttribute("Description", "Atualizar venda cancelada retorna 409")]
        public async global::System.Threading.Tasks.Task AtualizarVendaCanceladaRetorna409()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar venda cancelada retorna 409", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync("que existe uma venda cadastrada e ela foi cancelada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 40
    await testRunner.WhenAsync("eu tentar atualizar a venda cancelada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 41
    await testRunner.ThenAsync("a resposta de atualização deve ter status 409", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 42
    await testRunner.AndAsync("o tipo do erro de atualização deve ser \"sale_state_conflict\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar quantidade de item recalcula desconto e total")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualizar venda")]
        [Xunit.TraitAttribute("Description", "Atualizar quantidade de item recalcula desconto e total")]
        public async global::System.Threading.Tasks.Task AtualizarQuantidadeDeItemRecalculaDescontoETotal()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar quantidade de item recalcula desconto e total", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
    await testRunner.GivenAsync("que existe uma venda cadastrada com um item de quantidade 2 e preço 10.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 46
    await testRunner.WhenAsync("eu atualizar a venda com quantidade 10 do mesmo item", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 47
    await testRunner.ThenAsync("a resposta de atualização deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 48
    await testRunner.AndAsync("o totalAmount da venda retornada deve ser 80.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 49
    await testRunner.AndAsync("o desconto do item na resposta deve ser 20%", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar venda adicionando novo item atualiza total")]
        [Xunit.TraitAttribute("FeatureTitle", "Atualizar venda")]
        [Xunit.TraitAttribute("Description", "Atualizar venda adicionando novo item atualiza total")]
        public async global::System.Threading.Tasks.Task AtualizarVendaAdicionandoNovoItemAtualizaTotal()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar venda adicionando novo item atualiza total", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
    await testRunner.GivenAsync("que existe uma venda cadastrada com um item de quantidade 1 e preço 10.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 53
    await testRunner.WhenAsync("eu atualizar a venda incluindo um segundo item de quantidade 5 e preço 20.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 54
    await testRunner.ThenAsync("a resposta de atualização deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 55
    await testRunner.AndAsync("o totalAmount da venda retornada deve ser 100.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 56
    await testRunner.AndAsync("a venda no banco deve conter 2 itens", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AtualizarVendaFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AtualizarVendaFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
